version: 2
jobs:
    setup_dependencies:
        docker:
            - image: kagalpandh/kacpp-cppdev
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    pip install -r requirements.txt
                    python3 -m pip install -U git+git://github.com/python/mypy.git
                    pip install -e .
            - save_cache:
                key: deps-{{ checksum "requirements.txt" }}
                paths:
                    - "~/.local"
    test:
        docker:
            - image: kagalpandh/kacpp-cppdev
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    python3 -m unittest discover tests -v
    thint:
        docker:
            - image: kagalpandh/kacpp-cppdev
        steps:
            - checkout
            - restore_cache:
                key: deps-{{ checksum "requirements.txt" }}
            - run:
                command: |
                    mypy --config-file=mypy.ini libpyka
workflows:
  version: 2
  all:
    jobs:
        - setup_dependencies
        - test:
            requires:
                - setup_dependencies
        - thint:
            requires:
                - test


